### ISSUE TITLE
setting the environment variables

### ISSUE THREAD

**Issue by pishty1** [open-runtimes/open-runtimes#81]
Hello guys, Im currently using openruntimes to develop and deploy functions locally. I have 2 questions that i cant seem to find an answer to in the docs.
1) currently when i change the code of my cloud function, i restart the docker container to see the changes. just wondering what the normal workflow is when developing cloud functions. Is everyone restarting the container to check every code change or is there a quicker workflow ? Im guessing there is no unit test like workflow to quickly test the code as you write it
2) how do i set up the env variables so that i see them in req.env (nodejs 16)  currently when the function is called the req.env is empty.

This is my current docker compose

```
version: '3'

services:
  open-runtimes-node-16.0:
    container_name: open-runtimes-node-16.0
    build:
      context: .
    ports: 
      - 3000:3000
    environment:
      - INTERNAL_RUNTIME_KEY=secret-key
      - INTERNAL_RUNTIME_ENTRYPOINT=src/index.js
      - APPWRITE_API_KEY=my_api_key
      - APPWRITE_FUNCTION_PROJECT_ID=myproj_key
      - APPWRITE_FUNCTION_ENDPOINT=my_endpoint
    volumes:
      - ./example/:/usr/code:rw
    command: sh -c "sh /usr/local/src/build.sh && cp /usr/code/code.tar.gz /tmp/code.tar.gz && sh /usr/local/src/start.sh"
```

many thanks in advance
